# Generated by Django 2.2.6 on 2019-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='traveldatefrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='traveldateto',
            field=models.DateField(),
        ),
    ]
