# Generated by Django 2.2.6 on 2019-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddyApp', '0002_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='traveldatefrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='traveldateto',
            field=models.DateTimeField(),
        ),
    ]
